projects:
  awsamplifyexperiment:
    schemaPath: graphql/schema.json
    includes:
      - Brainfy
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
